apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io 
parameters:
  server: 192.168.20.121 # Remplacer par l'adresse IP du serveur NFS
  share: /data
reclaimPolicy: Delete # Kubernetes supprime automatiquement le volume.
reclaimPolicy: Retain # Le volume doit être supprimé manuellement
volumeBindingMode: Immediate # volume créé dès la demande
volumeBindingMode: WaitForFirstConsumer # volume créé uniquement quand un Pod l'utilise
allowVolumeExpansion: true # agrandir le volume après création ?
mountOptions:
  - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deployment-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi # StorageClass NFS définie précédemment