apiVersion: v1
kind: Service
metadata:
  name: todos-app-service
  namespace: todos
  labels:
    app: todos-app
spec:
  type: LoadBalancer
  selector:
    app: todos-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
