apiVersion: v1
kind: Service
metadata:
  name: todos-app-service 
  namespace: todos
spec:
  type: ClusterIP 
  selector:
    app: todos-app
  ports:
    - name: http
      port: 80         
      targetPort: 8080 